version: '3.8'
services:
  labcheck-pwa:
    build: .
    restart: unless-stopped
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    labels:
      - "com.docker.compose.service=labcheck-pwa"
      - "description=LabCheck Progressive Web App - Student Sign-In System"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # volumes:
      # Optional: Mount for logs (uncomment if needed)
      # - ./logs:/var/log/nginx
