version: '3.8'
services:
  labcheck-pwa:
    build: .
    restart: unless-stopped
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.labcheck-pwa.rule=Host(`lab.johnnyrobot.ai`)"
      - "traefik.http.routers.labcheck-pwa.entrypoints=http"
      - "traefik.http.routers.labcheck-pwa.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.labcheck-pwa-secure.rule=Host(`lab.johnnyrobot.ai`)"
      - "traefik.http.routers.labcheck-pwa-secure.entrypoints=https"
      - "traefik.http.routers.labcheck-pwa-secure.tls=true"
      - "traefik.http.routers.labcheck-pwa-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.labcheck-pwa.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "com.docker.compose.service=labcheck-pwa"
      - "description=LabCheck Progressive Web App - Student Sign-In System"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # volumes:
      # Optional: Mount for logs (uncomment if needed)
      # - ./logs:/var/log/nginx
